import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "@/components/navigation/SideBar";
import { RadioPlayer } from "@/components/RadioPlayer";
import { Input } from "@/components/ui/input";
import { Search } from "lucide-react";
import Image from "next/image";
import { karla } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={karla.className}>
      <body className={`antialiased !pointer-events-auto min-h-screen pb-radioplayer-height-md`}>
        <div className="flex flex-col md:flex-row max-w-container-width mx-auto">
          <Sidebar />
          <div className="flex-1">
            <div className="hidden md:flex w-full bg-greyspace h-logo-container-height-md items-center justify-center">
              <div className="relative h-[90px] w-full max-w-[728px] bg-gray-300">
                <Image src={`https://picsum.photos/600/400?random=${Math.floor(Math.random() * 10) + 1}`} alt="Sample"
                  fill
                  className="inset-0 object-cover" />
              </div>
            </div>
            <div className="sticky top-0 z-50">
              <div className="flex w-full gap-5 bg-greyspace h-searchbar-container-height items-center">
                <div className="px-5 flex-1 relative">
                  <Input placeholder="Search..." className="bg-white shadow-none border-0 pr-8" />
                  <Search className="absolute right-5 top-1/2 -translate-y-1/2 w-4 h-4 text-black mr-2" />
                </div>
                <div className="hidden xl:block xl:w-right-sidebar-width" />
              </div>
            </div>
            {children}
          </div>
          <RadioPlayer />
        </div>

      </body>
    </html>
  );
}
